language: c++

addons:
  apt:
    update: true
    packages:
      - clang
      - gcc-12
      - g++-12

jobs:
  include:
    - name: "Clang Build"
      os: linux
      dist: jammy
      env:
        - CC=gcc-12
        - CXX=g++-12
      script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
    - name: "GCC Build"
      os: linux
      dist: jammy
      env:
        - CC=gcc-12
        - CXX=g++-12
      script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
    - name: "Docker Build"
      os: linux
      dist: jammy
      script:
        - docker build . --build-arg GITHUB_USER_PASSWORD
