language: c++

cache:
  ccache: true

env:
  global:
    - CMAKE_C_COMPILER_LAUNCHER=ccache
    - CMAKE_CXX_COMPILER_LAUNCHER=ccache

addons:
  apt:
    update: true
    packages:
      - clang
      - python3
      - python3-pip
      - gcc-12
      - g++-12

jobs:
  include:
    - name: "Clang Build"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      install:
        - pip3 install --user gitpython requests
      script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
    - name: "GCC Build"
      os: linux
      dist: jammy
      env:
        - CC=gcc-12
        - CXX=g++-12
      install:
        - pip3 install --user gitpython requests
      script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
    - name: "Docker Build"
      os: linux
      dist: jammy
      script:
        - docker build . --build-arg GITHUB_USER_PASSWORD
