language: c++

addons:
  apt:
    packages:
      - libgflags-dev
      - python3
      - python3-pip
      - python3-setuptools
    update: true

jobs:
  include:
    - os: linux
      dist: focal
      env:
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11"
    - os: linux
      dist: bionic
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
    - os: linux
      dist: focal
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

before_install:
  eval "${MATRIX_EVAL}"

install:
  - ci/install.sh

script:
  - ci/build.sh
