language: c++

addons:
  apt:
    packages:
      - clang
      - clang-format
      - llvm
      - python3
      - python3-pip
    update: true

jobs:
  include:
    - os: linux
      dist: jammy
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: linux
      dist: jammy
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
    - os: linux
      dist: jammy
      env:
        - BUILD_DOCKER=1

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - tools/ci/install.sh

script:
  - tools/ci/build.sh
