language: c++

cache:
  ccache: true
  pip: true
  directories:
    - $HOME/.hunter

addons:
  apt:
    packages:
      - libgflags-dev
    update: true

jobs:
  include:
    - os: linux
      dist: focal
      env:
        - RUN_TYPE=coverage
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11"
    - os: linux
      dist: bionic
      env:
        - RUN_TYPE=test
        - MATRIX_EVAL="CC=gcc && CXX=g++"
    - os: linux
      dist: focal
      env:
        - RUN_TYPE=test
        - MATRIX_EVAL="CC=gcc && CXX=g++"
    - os: linux
      dist: focal
      env:
        - RUN_TYPE=test
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11"

before_install:
  eval "${MATRIX_EVAL}"

install:
  - ci/install.sh

script:
  - ci/build.sh
